###

GET http://localhost:3000/todos/

###

GET http://localhost:3000/todos/6

###

GET http://localhost:3000/agenda/?date=2021-4-2

###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 7,
  "todo": "Finalize event",
  "priority": "HIGH",
  "status": "DONE",
  "category": "HOME",
  "dueDate": "2021-2-22"
}

###

PUT http://localhost:3000/todos/6
Content-Type: application/json

{
    "status": "DONE"
}
###

DELETE http://localhost:3000/todos/7